// CI pipeline for ekart application...
pipeline {
    agent any

    // we need to define the tools as we are using them in the stages...
    tools {
        // tool's name
        jdk 'jdk17'
        maven 'mvn3'
    }

    environment {
        // environment variable required in the stages...
        SCANNER_HOME= tool 'sonarqube-scanner'
    }

    stages {
        // fetch the latest code for the development...
        stage('Git checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/jaiswaladi246/Ekart'
                // update the nexus server ip in pom.xml file...
                sh "sed -i 's/3.108.254.192/192.168.0.114/g' pom.xml"
            }
        }

        // compiling the code using maven...
        stage('Compile') {
            steps {
                sh "mvn compile"
            }
        }

        // code quality check...
        stage('Sonarqube analysis') {
            steps {
                // name of the sonarqube server...
                withSonarQubeEnv('sonarqube-server') {
                    sh ''' $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=ekart -Dsonar.java.binaries=. \
                -Dsonar.projectKey=ekart '''
                }
            }
        }

        // security analysis...
        stage('Dependency check') {
            steps {
                dependencyCheck additionalArguments: ' --scan ./' , odcInstallation: 'dp-check' // tool's name
                dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
            }
        }

        // file-system scanning using trivy
        stage('Trivy filesystem scan') {
            steps {
                sh "trivy fs ."
            }
        }

        // package application...
        stage('Package application') {
            steps {
                // sh "mvn clean install -DskipTests=true"
                sh "mvn package -DskipTests=true"
            }
        }

        // build archive and deploy to nexus...
        stage('Build archive & update Nexus') {
            steps {
                withMaven(globalMavenSettingsConfig: 'maven-global-setting.xml') {
                    sh "mvn deploy -DskipTests=true"
                }
            }
        }

        // build docker image...
        stage('Build image') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'docker-cred', toolName: 'docker') {
                        sh "docker push minex970/ekart:latest"
                    }
                }
            }
        }

        // Scanning image using trivy...
        stage('Trivy image scanner') {
            steps {
                retry(3) {
                    sh "trivy image minex970/ekart:latest"
                }
            }
        }

        // push docker image...
        stage('Push image') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'docker-cred', toolName: 'docker') {
                        sh "docker push minex970/ekart:latest"
                    }
                }
            }
        }

        // trigger CD pipeline...
        stage('Trigger CD pipeline') {
            steps {
                build job: "Ekart-CD-pipeline"
            }
        }
    }
}
